### ISSUE TITLE
Italian typo from - Astrokiwi blog comment

### ISSUE THREAD

**Issue by valvin1** [Deevad/peppercarrot_ep22_translation#14]
@cgand Astrokiwi reports typo error in it translation  [here](https://www.peppercarrot.com/en/article412/episode-22-the-voting-system#c0412-1364) I think you are the one to check it :) 

> 
> About translations, I've just noticed some little mistakes in the italian version (nothing so serious, just typos I guess): in the 4th panel is written "si" instead of the correct form "sì", and "ninete" in the 6th one instead of the correct form "niente". In the 27th panel should be more correct to write "dopotutto" instead of "dopo tutto" (http://comesiscrive.it/dubbi/dopotutto-o-dopo-tutto/), but it is correct anyway, just a subtlety :)
> 
> Last but not least, in panel 31st is written "magnificol" instead of the correct form "magnifico".

**Comment by cgand** [comment]
Fixed in master, thanks to Astrokiwi.
Typos happens, too much really this time :-(

**Comment by Deevad** [comment]
Thank you very much @valvin1 and @cgand ; and no problem for typo: I'm the first one to make a ton of them. It's hard to re-read all with the SVG only until it's published. Thank you for the translation and the quick maintenance. I rendered and pushed online the fix.
