### ISSUE TITLE
Missing phrase in german translation page 6

### ISSUE THREAD

**Issue by cgand** [Deevad/peppercarrot_ep22_translation#15]
@colognella On last panel of page 6 episode 22 of german translation is missing the phrase “We now turn to Spirulina!”

**Comment by colognella** [comment]
@Deevad, something not ok? It does not show up in the panel.

**Comment by Deevad** [comment]
Hey @colognella ; I'm right now cleaning all the translation SVGs of all Pepper&Carrot ( over 8000 files ) in background. Sometime my actions of the moment can affect the renderfarm and the upload script ( the SVG on Github reveives a lot of post-process on my computer before going online and then are sent via FTP to the peppercarrot server ). I think one of my action of yesterday affected the rendering of this pull request. Sorry, totally my fault. I fixed it. Thank you for double checking. 

It's online now: https://www.peppercarrot.com/de/article412/episode-22-the-voting-system
